config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :spots
  root 'spots#index'
  get 'last', :to => 'spots#last'
  get 'map', :to => 'spots#map'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spot.rb
class Spot < ActiveRecord::Base
  validates :user_id, presence: true
  validates :image, presence: true
  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  belongs_to :user
  geocoded_by :adress
  after_validation :geocode
   validates :adress, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: true, length: { minimum: 2, maximum: 16 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :spots, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [ :new, :edit, :destroy, :create]
  def last
  @spots = Spot.all
  end

  def new
    @spot = current_user.spots.build
  end
  def map
  @spots = Spot.all
  @hash = Gmaps4rails.build_markers(@spots) do |spot, marker|
  marker.lat spot.latitude
  marker.lng spot.longitude
  marker.infowindow spot.title
  end
  end
  def show
  @spot = Spot.find(params[:id])
  end
  def create
    @spot = current_user.spots.build(spot_params)
    if @spot.save
      redirect_to spot_path(@spot)
    else
      redirect_to new_spot_path
    end
  end
  def edit
    @spot = Spot.find(params[:id])
  end
  def update
    @spot = Spot.find(params[:id])
    @spot.update(spot_params)
    redirect_to(spot_path(@spot))
  end
  def destroy
  @spot = Spot.find(params[:id])
  @spot.destroy
  redirect_to spots_path
  end
  private
  def spot_params
  params.require(:spot).permit(:title, :date, :image, :adress, :latitude, :longitude)
  end
  def set_spot
    @spot = Spot.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>UFO Spotted! - MMI Bordeaux</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %><link href="/assets/stylesheets/application.css" rel="stylesheet">
    <link rel="shortcut icon" href="favicon.ico">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= yield %>

    <script src="/js/jquery-1.11.3.min.js"></script>
    <script src="/js/jquery.placeholder.js"></script>
    <script src="/js/custom.js"></script>

  </body>
</html>

app/views/spots/edit.html.erb
<div class="wrapper">

        <div class="ufo-text">

          <%= link_to root_path do %>
            <img src="/images/logo.png" style="width:250px;" class="logo" alt="">
          <% end %>

          <% unless user_signed_in? %>
            <h1>made in Bordeaux with</h1>
            <span class="lines">RUBY ON RAILS</span>
          <% end %>

          <% if user_signed_in? %>
            <h1>Welcome, <%= current_user.user_name %></h1>
            <span class="lines">
            <%= link_to 'Log Out', destroy_user_session_path(:authenticity_token => form_authenticity_token()), method: 'delete' %>
            </span>
          <% end %>

          <div class="menu">
            <nav>
              <ul>
                <li><%= link_to root_path do %><i class="fas fa-home"></i> Home<% end %></li>
                <li><%= link_to last_path do %><i class="far fa-clock"></i> Last<% end %></li>
                <li><%= link_to map_path do %><i class="fas fa-map-marker-alt"></i> Map<% end %></li>
              </ul>
            </nav>
          </div>

        </div>

        <img src="/images/ufo.png" class="ufo2" alt="">

</div>

<div class="new">

  <% if user_signed_in? %>
        <% unless current_user.admin? %>
           <% if @spot.user.id == current_user.id %>
              <%= simple_form_for @spot do |f| %>
              <%= f.input :title, :placeholder => 'ex : UFO in my garden OMG !', :class => 'input' %><br><br>
              <%= f.input :date %><br><br>
              <%= f.input :adress, :placeholder => 'ex : Place de la bourse bordeaux france' %><br><br>
              <%= f.submit "Update", :class => 'button-new' %>
              <%= link_to spot_path(@spot), method: :delete, data: { confirm: "Are you sure you want to delete this spot?" } do %>
              <i class="fas fa-trash-alt" style="margin-left:20px;font-size:20px;"></i><% end %>
              <% end %>
           <% end %>
        <% end %>
           <% if current_user.admin? %>
             <%= simple_form_for @spot do |f| %>
             <%= f.input :title, :placeholder => 'ex : UFO in my garden OMG !', :class => 'input' %><br><br>
             <%= f.input :date %><br><br>
             <%= f.input :adress, :placeholder => 'ex : Place de la bourse bordeaux france' %><br><br>
             <%= f.submit "Update", :class => 'button-new' %>
             <%= link_to spot_path(@spot), method: :delete, data: { confirm: "Are you sure you want to delete this spot?" } do %>
             <i class="fas fa-trash-alt" style="margin-left:20px;font-size:20px;"></i><% end %>
             <% end %>
           <% end %>
  <% end %>

</div>

app/views/spots/index.html.erb
<script type="text/javascript">if (location.href.indexOf('reload')==-1){location.href=location.href+'?reload';}</script>
<div class="bordeaux">
      <div class="wrapper">
        <div class="ufo-text">

          <%= link_to root_path do %>
          <img src="/images/logo.png" style="width:250px;" class="logo" alt="">
          <% end %>

          <% unless user_signed_in? %>
            <h1>made in Bordeaux with</h1>
            <span class="lines">RUBY ON RAILS</span>
          <% end %>

          <% if user_signed_in? %>
            <h1>Welcome, <%= current_user.user_name %></h1>
            <span class="lines">
            <%= link_to 'Log Out', destroy_user_session_path(:authenticity_token => form_authenticity_token()), method: 'delete' %>
            </span>
          <% end %>

          <div class="menu">
            <nav>
              <ul>
                <li><%= link_to root_path do %><i class="fas fa-home"></i> Home<% end %></li>
                <li><%= link_to last_path do %><i class="far fa-clock"></i> Last<% end %></li>
                <li><%= link_to map_path do %><i class="fas fa-map-marker-alt"></i> Map<% end %></li>
              </ul>
            </nav>
          </div>

            <%= link_to new_spot_path do %>
            <button type="submit" class="button-new"><i class="fas fa-crosshairs"></i> Spot new UFO</button>
            <% end %>

        </div>

            <img src="/images/light.png" class="light" alt="">
            <img src="/images/ufo.png" class="ufo" alt="">

      </div>
</div>

app/views/spots/last.html.erb
<div class="wrapper">

        <div class="ufo-text">

          <%= link_to root_path do %>
            <img src="/images/logo.png" style="width:250px;" class="logo" alt="">
          <% end %>

          <% unless user_signed_in? %>
            <h1>made in Bordeaux with</h1>
            <span class="lines">RUBY ON RAILS</span>
          <% end %>

          <% if user_signed_in? %>
            <h1>Welcome, <%= current_user.user_name %></h1>
            <span class="lines">
            <%= link_to 'Log Out', destroy_user_session_path(:authenticity_token => form_authenticity_token()), method: 'delete' %>
            </span>
          <% end %>

          <div class="menu">
            <nav>
              <ul>
                <li><%= link_to root_path do %><i class="fas fa-home"></i> Home<% end %></li>
                <li><%= link_to last_path do %><i class="far fa-clock"></i> Last<% end %></li>
                <li><%= link_to map_path do %><i class="fas fa-map-marker-alt"></i> Map<% end %></li>
              </ul>
            </nav>
          </div>

        </div>

        <img src="/images/ufo.png" class="ufo2" alt="">

</div>

<% @spots.each do |spot| %>

  <div class="spot">
    <h1><%= link_to spot_path(spot) do %><%= spot.title %><% end %> <span class="author">Spotted by <i class="fas fa-user"></i> <%= spot.user.user_name %></span></h1>
    <p class="date"><%= spot.date %><p>
    <div class="photo" style="background-image:url(<%= spot.image.url(:medium) %>);background-repeat:no-repeat;background-size:cover;background-position:center;"></div>
    <%= link_to map_path do %>
    <div class="location" style="background-image:url(https://maps.googleapis.com/maps/api/staticmap?key=AIzaSyBgn6ogRGTCN2TovzkXwUe5ovwencVQr1c&center=<%= spot.latitude %>,<%= spot.longitude %>&zoom=12&format=png&maptype=roadmap&style=element:geometry%7Ccolor:0x242f3e&style=element:labels.text.fill%7Ccolor:0x746855&style=element:labels.text.stroke%7Ccolor:0x242f3e&style=feature:administrative.locality%7Celement:labels.text.fill%7Ccolor:0xd59563&style=feature:poi%7Celement:labels.text.fill%7Ccolor:0xd59563&style=feature:poi.park%7Celement:geometry%7Ccolor:0x263c3f&style=feature:poi.park%7Celement:labels.text.fill%7Ccolor:0x6b9a76&style=feature:road%7Celement:geometry%7Ccolor:0x38414e&style=feature:road%7Celement:geometry.stroke%7Ccolor:0x212a37&style=feature:road%7Celement:labels.text.fill%7Ccolor:0x9ca5b3&style=feature:road.highway%7Celement:geometry%7Ccolor:0x746855&style=feature:road.highway%7Celement:geometry.stroke%7Ccolor:0x1f2835&style=feature:road.highway%7Celement:labels.text.fill%7Ccolor:0xf3d19c&style=feature:transit%7Celement:geometry%7Ccolor:0x2f3948&style=feature:transit.station%7Celement:labels.text.fill%7Ccolor:0xd59563&style=feature:water%7Celement:geometry%7Ccolor:0x17263c&style=feature:water%7Celement:labels.text.fill%7Ccolor:0x515c6d&style=feature:water%7Celement:labels.text.stroke%7Ccolor:0x17263c&size=510x500&markers=color:red%7Clabel:C%7C<%= spot.latitude %>,<%= spot.longitude %>);background-repeat:no-repeat;background-size:cover;background-position:center;float:right;"></div>
    <% end %>
  </div>
<% end %>

app/views/spots/map.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyBgn6ogRGTCN2TovzkXwUe5ovwencVQr1c"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <script src="/js/underscore.js?v=1001"></script>
    <script type="text/javascript">if (location.href.indexOf('reload')==-1){location.href=location.href+'?reload';}</script>
<div class="wrapper">

        <div class="ufo-text">

          <%= link_to root_path do %>
            <img src="/images/logo.png" style="width:250px;" class="logo" alt="">
          <% end %>

          <% unless user_signed_in? %>
            <h1>made in Bordeaux with</h1>
            <span class="lines">RUBY ON RAILS</span>
          <% end %>

          <% if user_signed_in? %>
            <h1>Welcome, <%= current_user.user_name %></h1>
            <span class="lines">
            <%= link_to 'Log Out', destroy_user_session_path(:authenticity_token => form_authenticity_token()), method: 'delete' %>
            </span>
          <% end %>

          <div class="menu">
            <nav>
              <ul>
                <li><%= link_to root_path do %><i class="fas fa-home"></i> Home<% end %></li>
                <li><%= link_to last_path do %><i class="far fa-clock"></i> Last<% end %></li>
                <li><%= link_to map_path do %><i class="fas fa-map-marker-alt"></i> Map<% end %></li>
              </ul>
            </nav>
          </div>

        </div>

        <img src="/images/ufo.png" class="ufo2" alt="">

</div>

      <div class='new'>
  <div id="map" style='width: 100%; height: 500px;'></div>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {styles: [{"elementType": "geometry","stylers": [{"color": "#242f3e"}]},{"elementType": "labels.text.fill","stylers": [{"color": "#746855"}]},{"elementType": "labels.text.stroke","stylers": [{"color": "#242f3e"}]},{"featureType": "administrative.locality","elementType": "labels.text.fill","stylers": [{"color": "#d59563"}]},{"featureType": "poi","elementType": "labels.text.fill","stylers": [{"color": "#d59563"}]},{"featureType": "poi.park","elementType": "geometry","stylers": [{"color": "#263c3f"}]},{"featureType": "poi.park","elementType": "labels.text.fill","stylers": [{"color": "#6b9a76"}]},{"featureType": "road","elementType": "geometry","stylers": [{"color": "#38414e"}]},{"featureType": "road","elementType": "geometry.stroke","stylers": [{"color": "#212a37"}]},{"featureType": "road","elementType": "labels.text.fill","stylers": [{"color": "#9ca5b3"}]},{"featureType": "road.highway","elementType": "geometry","stylers": [{"color": "#746855"}]},{"featureType": "road.highway","elementType": "geometry.stroke","stylers": [{"color": "#1f2835"}]},{"featureType": "road.highway","elementType": "labels.text.fill","stylers": [{"color": "#f3d19c"}]},{"featureType": "transit","elementType": "geometry","stylers": [{"color": "#2f3948"}]},{"featureType": "transit.station","elementType": "labels.text.fill","stylers": [{"color": "#d59563"}]},{"featureType": "water","elementType": "geometry","stylers": [{"color": "#17263c"}]},{"featureType": "water","elementType": "labels.text.fill","stylers": [{"color": "#515c6d"}]},{"featureType": "water","elementType": "labels.text.stroke","stylers": [{"color": "#17263c"}]}]}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/spots/new.html.erb
<div class="wrapper">

        <div class="ufo-text">

          <%= link_to root_path do %>
            <img src="/images/logo.png" style="width:250px;" class="logo" alt="">
          <% end %>

          <% unless user_signed_in? %>
            <h1>made in Bordeaux with</h1>
            <span class="lines">RUBY ON RAILS</span>
          <% end %>

          <% if user_signed_in? %>
            <h1>Welcome, <%= current_user.user_name %></h1>
            <span class="lines">
            <%= link_to 'Log Out', destroy_user_session_path(:authenticity_token => form_authenticity_token()), method: 'delete' %>
            </span>
          <% end %>

          <div class="menu">
            <nav>
              <ul>
                <li><%= link_to root_path do %><i class="fas fa-home"></i> Home<% end %></li>
                <li><%= link_to last_path do %><i class="far fa-clock"></i> Last<% end %></li>
                <li><%= link_to map_path do %><i class="fas fa-map-marker-alt"></i> Map<% end %></li>
              </ul>
            </nav>
          </div>

        </div>

        <img src="/images/ufo.png" class="ufo2" alt="">

</div>

      <div class="new">
        <%= simple_form_for @spot do |f| %>
  <%= f.input :title, :placeholder => 'ex : UFO in my garden OMG !' %><br><br>
  <%= f.input :date %><br><br>
  <%= f.input :adress, :placeholder => 'ex : Place de la bourse bordeaux france' %><br><br>
  <%= f.input :image, as: :file %><br><br>
  <%= f.submit "Spot!", :class => 'button-new' %>
<% end %>
      </div>

app/views/spots/show.html.erb
<div class="wrapper">

        <div class="ufo-text">

          <%= link_to root_path do %>
            <img src="/images/logo.png" style="width:250px;" class="logo" alt="">
          <% end %>

          <% unless user_signed_in? %>
            <h1>made in Bordeaux with</h1>
            <span class="lines">RUBY ON RAILS</span>
          <% end %>

          <% if user_signed_in? %>
            <h1>Welcome, <%= current_user.user_name %></h1>
            <span class="lines">
            <%= link_to 'Log Out', destroy_user_session_path(:authenticity_token => form_authenticity_token()), method: 'delete' %>
            </span>
          <% end %>

          <div class="menu">
            <nav>
              <ul>
                <li><%= link_to root_path do %><i class="fas fa-home"></i> Home<% end %></li>
                <li><%= link_to last_path do %><i class="far fa-clock"></i> Last<% end %></li>
                <li><%= link_to map_path do %><i class="fas fa-map-marker-alt"></i> Map<% end %></li>
              </ul>
            </nav>
          </div>

        </div>

        <img src="/images/ufo.png" class="ufo2" alt="">

</div>

  <div class="spot">
    <h1><%= @spot.title %> <span class="author">Spotted by <i class="fas fa-user"></i> <%= @spot.user.user_name %></span></h1>
    <p class="date"><%= @spot.date %><p>

      <% if user_signed_in? %>
        <% unless current_user.admin? %>
            <% if @spot.user.id == current_user.id %>
                <%= link_to "Edit", edit_spot_path(@spot), :class => 'button-new edit' %>
            <% end %>
        <% end %>
        <% if current_user.admin? %>
            <%= link_to "Edit", edit_spot_path(@spot), :class => 'button-new edit' %>
        <% end %>
      <% end %>

    <div class="photo" style="background-image:url(<%= @spot.image.url(:medium) %>);background-repeat:no-repeat;background-size:cover;background-position:center;"></div>
    <%= link_to map_path do %>
    <div class="location" style="background-image:url(https://maps.googleapis.com/maps/api/staticmap?key=AIzaSyBgn6ogRGTCN2TovzkXwUe5ovwencVQr1c&center=<%= @spot.latitude %>,<%= @spot.longitude %>&zoom=12&format=png&maptype=roadmap&style=element:geometry%7Ccolor:0x242f3e&style=element:labels.text.fill%7Ccolor:0x746855&style=element:labels.text.stroke%7Ccolor:0x242f3e&style=feature:administrative.locality%7Celement:labels.text.fill%7Ccolor:0xd59563&style=feature:poi%7Celement:labels.text.fill%7Ccolor:0xd59563&style=feature:poi.park%7Celement:geometry%7Ccolor:0x263c3f&style=feature:poi.park%7Celement:labels.text.fill%7Ccolor:0x6b9a76&style=feature:road%7Celement:geometry%7Ccolor:0x38414e&style=feature:road%7Celement:geometry.stroke%7Ccolor:0x212a37&style=feature:road%7Celement:labels.text.fill%7Ccolor:0x9ca5b3&style=feature:road.highway%7Celement:geometry%7Ccolor:0x746855&style=feature:road.highway%7Celement:geometry.stroke%7Ccolor:0x1f2835&style=feature:road.highway%7Celement:labels.text.fill%7Ccolor:0xf3d19c&style=feature:transit%7Celement:geometry%7Ccolor:0x2f3948&style=feature:transit.station%7Celement:labels.text.fill%7Ccolor:0xd59563&style=feature:water%7Celement:geometry%7Ccolor:0x17263c&style=feature:water%7Celement:labels.text.fill%7Ccolor:0x515c6d&style=feature:water%7Celement:labels.text.stroke%7Ccolor:0x17263c&size=510x500&markers=color:red%7Clabel:C%7C<%= @spot.latitude %>,<%= @spot.longitude %>);background-repeat:no-repeat;background-size:cover;background-position:center;float:right;"></div>
    <% end %>

  </div>